#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aniso8601
Version  : 3.0.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/1e/12/a212cf206d67e368b851ad1b3e2560c343021a48bc2581e5184056cf8ced/aniso8601-3.0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/1e/12/a212cf206d67e368b851ad1b3e2560c343021a48bc2581e5184056cf8ced/aniso8601-3.0.2.tar.gz
Summary  : A library for parsing ISO 8601 strings.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: aniso8601-python3
Requires: aniso8601-license
Requires: aniso8601-python
Requires: python-dateutil
BuildRequires : buildreq-distutils3

%description
aniso8601
        ===========
        
        ----------------------------------
        Another ISO 8601 parser for Python
        ----------------------------------
        
        Features
        ========
        * Pure Python implementation
        * Python 3 support
        * Logical behavior

%package license
Summary: license components for the aniso8601 package.
Group: Default

%description license
license components for the aniso8601 package.


%package python
Summary: python components for the aniso8601 package.
Group: Default
Requires: aniso8601-python3

%description python
python components for the aniso8601 package.


%package python3
Summary: python3 components for the aniso8601 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the aniso8601 package.


%prep
%setup -q -n aniso8601-3.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536550963
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/aniso8601
cp LICENSE %{buildroot}/usr/share/doc/aniso8601/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/aniso8601/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
