#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aniso8601
Version  : 4.0.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/b0/23/67f6d3b4b11578b13a7fe0c26a2f8c9becc61c4c601ccc8d8d23ca7ca54f/aniso8601-4.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/23/67f6d3b4b11578b13a7fe0c26a2f8c9becc61c4c601ccc8d8d23ca7ca54f/aniso8601-4.0.1.tar.gz
Summary  : A library for parsing ISO 8601 strings.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: aniso8601-license = %{version}-%{release}
Requires: aniso8601-python = %{version}-%{release}
Requires: aniso8601-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=========
        
        Another ISO 8601 parser for Python
        ----------------------------------
        
        Features
        ========
        * Pure Python implementation
        * Python 3 support
        * Logical behavior

%package license
Summary: license components for the aniso8601 package.
Group: Default

%description license
license components for the aniso8601 package.


%package python
Summary: python components for the aniso8601 package.
Group: Default
Requires: aniso8601-python3 = %{version}-%{release}

%description python
python components for the aniso8601 package.


%package python3
Summary: python3 components for the aniso8601 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the aniso8601 package.


%prep
%setup -q -n aniso8601-4.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540492842
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aniso8601
cp LICENSE %{buildroot}/usr/share/package-licenses/aniso8601/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aniso8601/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
