#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aniso8601
Version  : 4.1.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/7d/f6/7b91438c9bdd83b6e7147b46d20cdf04ab58c7150f1ecc65cb53be34b976/aniso8601-4.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/7d/f6/7b91438c9bdd83b6e7147b46d20cdf04ab58c7150f1ecc65cb53be34b976/aniso8601-4.1.0.tar.gz
Summary  : A library for parsing ISO 8601 strings.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: aniso8601-license = %{version}-%{release}
Requires: aniso8601-python = %{version}-%{release}
Requires: aniso8601-python3 = %{version}-%{release}
Requires: python-dateutil
BuildRequires : buildreq-distutils3
BuildRequires : python-dateutil

%description
aniso8601
=========
Another ISO 8601 parser for Python
----------------------------------

%package license
Summary: license components for the aniso8601 package.
Group: Default

%description license
license components for the aniso8601 package.


%package python
Summary: python components for the aniso8601 package.
Group: Default
Requires: aniso8601-python3 = %{version}-%{release}

%description python
python components for the aniso8601 package.


%package python3
Summary: python3 components for the aniso8601 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the aniso8601 package.


%prep
%setup -q -n aniso8601-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547159003
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aniso8601
cp LICENSE %{buildroot}/usr/share/package-licenses/aniso8601/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aniso8601/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
